// flow-typed signature: f474a492f0ea76bf3a8727cd3fa472ea
// flow-typed version: <<STUB>>/sql-query-identifier_v^1.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sql-query-identifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sql-query-identifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sql-query-identifier/lib/index' {
  declare module.exports: any;
}

declare module 'sql-query-identifier/lib/parser' {
  declare module.exports: any;
}

declare module 'sql-query-identifier/lib/tokenizer' {
  declare module.exports: any;
}

declare module 'sql-query-identifier/test/identifier/inner-statements.spec' {
  declare module.exports: any;
}

declare module 'sql-query-identifier/test/identifier/multiple-statement.spec' {
  declare module.exports: any;
}

declare module 'sql-query-identifier/test/identifier/single-statement.spec' {
  declare module.exports: any;
}

declare module 'sql-query-identifier/test/parser/multiple-statements.spec' {
  declare module.exports: any;
}

declare module 'sql-query-identifier/test/parser/single-statements.spec' {
  declare module.exports: any;
}

declare module 'sql-query-identifier/test/spec-helper' {
  declare module.exports: any;
}

declare module 'sql-query-identifier/test/tokenizer/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sql-query-identifier/lib/index.js' {
  declare module.exports: $Exports<'sql-query-identifier/lib/index'>;
}
declare module 'sql-query-identifier/lib/parser.js' {
  declare module.exports: $Exports<'sql-query-identifier/lib/parser'>;
}
declare module 'sql-query-identifier/lib/tokenizer.js' {
  declare module.exports: $Exports<'sql-query-identifier/lib/tokenizer'>;
}
declare module 'sql-query-identifier/test/identifier/inner-statements.spec.js' {
  declare module.exports: $Exports<'sql-query-identifier/test/identifier/inner-statements.spec'>;
}
declare module 'sql-query-identifier/test/identifier/multiple-statement.spec.js' {
  declare module.exports: $Exports<'sql-query-identifier/test/identifier/multiple-statement.spec'>;
}
declare module 'sql-query-identifier/test/identifier/single-statement.spec.js' {
  declare module.exports: $Exports<'sql-query-identifier/test/identifier/single-statement.spec'>;
}
declare module 'sql-query-identifier/test/parser/multiple-statements.spec.js' {
  declare module.exports: $Exports<'sql-query-identifier/test/parser/multiple-statements.spec'>;
}
declare module 'sql-query-identifier/test/parser/single-statements.spec.js' {
  declare module.exports: $Exports<'sql-query-identifier/test/parser/single-statements.spec'>;
}
declare module 'sql-query-identifier/test/spec-helper.js' {
  declare module.exports: $Exports<'sql-query-identifier/test/spec-helper'>;
}
declare module 'sql-query-identifier/test/tokenizer/index.spec.js' {
  declare module.exports: $Exports<'sql-query-identifier/test/tokenizer/index.spec'>;
}
