// flow-typed signature: a159debaa2626b47714eb2fea2432b29
// flow-typed version: <<STUB>>/valida_v^2.4.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'valida'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'valida' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'valida/examples/groups' {
  declare module.exports: any;
}

declare module 'valida/examples/promise' {
  declare module.exports: any;
}

declare module 'valida/examples/sanitizer-toDate' {
  declare module.exports: any;
}

declare module 'valida/examples/sanitizer-toFloat' {
  declare module.exports: any;
}

declare module 'valida/examples/sanitizer-trim' {
  declare module.exports: any;
}

declare module 'valida/examples/schema' {
  declare module.exports: any;
}

declare module 'valida/examples/validator-array' {
  declare module.exports: any;
}

declare module 'valida/examples/validator-async' {
  declare module.exports: any;
}

declare module 'valida/examples/validator-date' {
  declare module.exports: any;
}

declare module 'valida/examples/validator-enum' {
  declare module.exports: any;
}

declare module 'valida/examples/validator-integer' {
  declare module.exports: any;
}

declare module 'valida/examples/validator-len' {
  declare module.exports: any;
}

declare module 'valida/examples/validator-range' {
  declare module.exports: any;
}

declare module 'valida/examples/validator-regex' {
  declare module.exports: any;
}

declare module 'valida/lib/context' {
  declare module.exports: any;
}

declare module 'valida/lib/index' {
  declare module.exports: any;
}

declare module 'valida/lib/sanitizers' {
  declare module.exports: any;
}

declare module 'valida/lib/valida-invalid-error' {
  declare module.exports: any;
}

declare module 'valida/lib/valida' {
  declare module.exports: any;
}

declare module 'valida/lib/validators' {
  declare module.exports: any;
}

declare module 'valida/spec/sanitizers.spec' {
  declare module.exports: any;
}

declare module 'valida/spec/validators.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'valida/examples/groups.js' {
  declare module.exports: $Exports<'valida/examples/groups'>;
}
declare module 'valida/examples/promise.js' {
  declare module.exports: $Exports<'valida/examples/promise'>;
}
declare module 'valida/examples/sanitizer-toDate.js' {
  declare module.exports: $Exports<'valida/examples/sanitizer-toDate'>;
}
declare module 'valida/examples/sanitizer-toFloat.js' {
  declare module.exports: $Exports<'valida/examples/sanitizer-toFloat'>;
}
declare module 'valida/examples/sanitizer-trim.js' {
  declare module.exports: $Exports<'valida/examples/sanitizer-trim'>;
}
declare module 'valida/examples/schema.js' {
  declare module.exports: $Exports<'valida/examples/schema'>;
}
declare module 'valida/examples/validator-array.js' {
  declare module.exports: $Exports<'valida/examples/validator-array'>;
}
declare module 'valida/examples/validator-async.js' {
  declare module.exports: $Exports<'valida/examples/validator-async'>;
}
declare module 'valida/examples/validator-date.js' {
  declare module.exports: $Exports<'valida/examples/validator-date'>;
}
declare module 'valida/examples/validator-enum.js' {
  declare module.exports: $Exports<'valida/examples/validator-enum'>;
}
declare module 'valida/examples/validator-integer.js' {
  declare module.exports: $Exports<'valida/examples/validator-integer'>;
}
declare module 'valida/examples/validator-len.js' {
  declare module.exports: $Exports<'valida/examples/validator-len'>;
}
declare module 'valida/examples/validator-range.js' {
  declare module.exports: $Exports<'valida/examples/validator-range'>;
}
declare module 'valida/examples/validator-regex.js' {
  declare module.exports: $Exports<'valida/examples/validator-regex'>;
}
declare module 'valida/lib/context.js' {
  declare module.exports: $Exports<'valida/lib/context'>;
}
declare module 'valida/lib/index.js' {
  declare module.exports: $Exports<'valida/lib/index'>;
}
declare module 'valida/lib/sanitizers.js' {
  declare module.exports: $Exports<'valida/lib/sanitizers'>;
}
declare module 'valida/lib/valida-invalid-error.js' {
  declare module.exports: $Exports<'valida/lib/valida-invalid-error'>;
}
declare module 'valida/lib/valida.js' {
  declare module.exports: $Exports<'valida/lib/valida'>;
}
declare module 'valida/lib/validators.js' {
  declare module.exports: $Exports<'valida/lib/validators'>;
}
declare module 'valida/spec/sanitizers.spec.js' {
  declare module.exports: $Exports<'valida/spec/sanitizers.spec'>;
}
declare module 'valida/spec/validators.spec.js' {
  declare module.exports: $Exports<'valida/spec/validators.spec'>;
}
